FROM node:20-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm ci
RUN npx prisma generate

COPY api ./api
COPY lib ./lib
COPY middleware ./middleware
COPY repositories ./repositories
COPY server ./server
COPY services ./services
COPY utils ./utils
COPY docker ./docker
COPY tsconfig.json ./

RUN chmod +x /app/docker/api-entrypoint.sh

EXPOSE 3001

CMD ["./docker/api-entrypoint.sh"]
