FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
COPY backend ./backend
COPY infra/docker ./docker
COPY tsconfig.json ./

RUN npm ci
RUN npx prisma generate --schema backend/prisma/schema.prisma

RUN chmod +x /app/docker/api-entrypoint.sh

EXPOSE 3000

CMD ["./docker/api-entrypoint.sh"]